const fruits = [
  {
    id: 1,
    title: 'Watermelon',
    category: '0-50 cal',
    calories: 30,
    img: 'https://images.pexels.com/photos/4966362/pexels-photo-4966362.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'Strawberries',
    category: '0-50 cal',
    calories: 32,
    img: 'https://images.pexels.com/photos/4038780/pexels-photo-4038780.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'Honeydew Melon',
    category: '0-50 cal',
    calories: 36,
    img: 'https://images.pexels.com/photos/7889978/pexels-photo-7889978.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },

  {
    id: 4,
    title: 'Yellow Peach',
    category: '0-50 cal',
    calories: 39,
    img: 'https://images.pexels.com/photos/4018832/pexels-photo-4018832.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },

  {
    id: 10,
    title: 'Banana',
    category: '50-100 cal',
    calories: 90,
    img: 'https://images.pexels.com/photos/4451846/pexels-photo-4451846.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 11,
    title: 'Grapes',
    category: '50-100 cal',
    calories: 67,
    img: 'https://images.pexels.com/photos/23042/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 12,
    title: 'Pear/Apple',
    category: '50-100 cal',
    calories: 63,
    img: 'https://images.pexels.com/photos/9508055/pexels-photo-9508055.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 13,
    title: 'Pineapple',
    category: '0-50 cal',
    calories: 49,
    img: 'https://images.pexels.com/photos/6157056/pexels-photo-6157056.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 14,
    title: 'Plums',
    category: '0-50 cal',
    calories: 46,
    img: 'https://images.pexels.com/photos/5945666/pexels-photo-5945666.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 9,
    title: 'Avocado',
    category: '100-200 cal',
    calories: 160,
    img: 'https://images.pexels.com/photos/2228553/pexels-photo-2228553.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 5,
    title: 'Dried Fruit',
    category: '200+ cal',
    calories: 349,
    img: 'https://images.pexels.com/photos/3872418/pexels-photo-3872418.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'Dates',
    category: '200+ cal',
    calories: 282,
    img: 'https://images.pexels.com/photos/4499224/pexels-photo-4499224.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'Dried Plums/Prune',
    category: '200+ cal',
    calories: 240,
    img: 'https://images.pexels.com/photos/4499211/pexels-photo-4499211.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'Dried Apple',
    category: '200+ cal',
    calories: 243,
    img: 'https://images.pexels.com/photos/7774131/pexels-photo-7774131.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 15,
    title: 'Raisins',
    category: '200+ cal',
    calories: 300,
    img: 'https://images.pexels.com/photos/10111853/pexels-photo-10111853.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
];
export default fruits;
